import { Feature } from "./feature.interface";

export const FEATURES_CONSTANT: Feature[] = [
  {
    name: "Projects",
    icon: "manage_history",
    title: "",
    description: "",
    roles: [],
  },
  { name: "Teams", icon: "groups", title: "", description: "", roles: [] },
  {
    name: "Dashboard",
    icon: "data_exploration",
    title: "",
    description: "",
    roles: [],
  },
  { name: "Backlogs", icon: "", title: "", description: "", roles: [] },
  {
    name: "Planning rooms",
    icon: "meeting_room",
    title: "",
    description: "",
    roles: [],
  },
  {
    name: "Grooming rooms",
    icon: "grain",
    title: "",
    description: "",
    roles: [],
  },
  {
    name: "Daily rooms",
    icon: "today",
    title: "",
    description: "",
    roles: [],
  },
  {
    name: "Review rooms",
    icon: "previews",
    title: "",
    description: "",
    roles: [],
  },
  {
    name: "Retrospective rooms",
    icon: "groups_3",
    title: "",
    description: "",
    roles: [],
  },
  {
    name: "Auto reports",
    icon: "smart_toy",
    title: "",
    description: "",
    roles: [],
  },
  { name: "History", icon: "history", title: "", description: "", roles: [] },
  {
    name: "Data export",
    icon: "file_download",
    title: "",
    description: "",
    roles: [],
  },
  {
    name: "Achievements",
    icon: "emoji_events",
    title: "",
    description: "",
    roles: [],
  },
  {
    name: "Resources",
    icon: "psychology_alt",
    title: "",
    description: "",
    roles: [],
  },
];
